"""trackers table

Revision ID: 3b44eaeed059
Revises: 
Create Date: 2019-09-28 12:09:06.017996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b44eaeed059'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracker_name', sa.String(length=64), nullable=True),
    sa.Column('root_url', sa.String(length=128), nullable=True),
    sa.Column('search_text', sa.String(length=128), nullable=True),
    sa.Column('min_price', sa.Numeric(precision=2), nullable=True),
    sa.Column('max_price', sa.Numeric(precision=2), nullable=True),
    sa.Column('notify_email', sa.String(length=64), nullable=True),
    sa.Column('notify_unit', sa.String(length=20), nullable=True),
    sa.Column('notify_interval', sa.Numeric(precision=2), nullable=True),
    sa.Column('last_notified', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracker')
    # ### end Alembic commands ###
